### ISSUE TITLE
Mejoras 

### ISSUE THREAD

**Issue by pilarsdiaz** [G0nov4/Queue_Visualization#1]
1 Creo que deberías limpiar la pantalla donde se introduce los números  
2 hay un error acepta la letra e y solo el signo de - y es un elemento vació

**Comment by G0nov4** [comment]
Issue #1 **arreglado** con validaciones de datos y mejoras en la **visualizacion de la cola**, gracias por el comentario.. :) 
Si tienes mas errores puedes comentar por aqui :+1:  :) :star:
